### ISSUE TITLE
Forms not processed with page caching because of nonce

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-pay-forms#3]
From customer:

> Sinds de laatste upgrade van Pronamic Pay wordt het formulierscherm 2x achter elkaar getoond aan donateurs, zodat ze 2x dezelfde gegevens (bedrag, naam, email, bank) moeten invullen - pas daarna gaan ze door naar het scherm om de betaalmethode te kiezen. Dit weerhoudt diverse mensen ervan om te doneren, omdat ze het 'verdacht' vinden dat de site / plug-in zo werkt.

The described issue seems to be caused by the `pronamic_pay_nonce` in forms. I was able to start the payment with the first form submit by using a random URL parameter for cache busting.

_Internal Help Scout ticket: https://secure.helpscout.net/conversation/2074253077/24820/_

**Comment by remcotolsma** [comment]
Related code:

https://github.com/pronamic/wp-pronamic-pay-forms/blob/4ed03aae52890c0096538d83004c692fd36e55b3/views/form.php#L264

https://github.com/pronamic/wp-pronamic-pay-forms/blob/4ed03aae52890c0096538d83004c692fd36e55b3/src/FormProcessor.php#L78-L87

Related StackExchange question:
https://wordpress.stackexchange.com/questions/123637/nonces-and-cache

**Comment by remcotolsma** [comment]
Discussed with @rvdsteeg @pronamic HQ, as far as we're concerned, the nonce can be removed for now.
